[package]
name = "ungrammar"
description = "A DSL for describing concrete syntax trees"
version = "1.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/matklad/ungrammar"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

exclude = ["/bors.toml", "/.github"]

[workspace]
members = ["ungrammar2json"]

[dependencies]
# nope
